In [2]:
#KERAS
import numpy as np
from numpy import genfromtxt

In [3]:
data=genfromtxt('bank_note_data.txt',delimiter=',')

In [4]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [5]:
label = data[:,4]

In [6]:
label

array([0., 0., 0., ..., 1., 1., 1.])

In [7]:
features=data[:,0:4]

In [8]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [9]:
X = features
y = label

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [12]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [13]:
len(X_train)

919

In [14]:
len(X_test)

453

In [15]:
len(y_train)

919

In [16]:
len(y_test)

453

In [17]:
from sklearn.preprocessing import MinMaxScaler

In [18]:
scaler=MinMaxScaler()

In [19]:
scaler.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [20]:
scaled_X_train=scaler.transform(X_train)

In [21]:
scaled_X_test=scaler.transform(X_test)

In [22]:
scaled_X_train.max()

1.0000000000000002

In [23]:
scaled_X_train

array([[4.44850688e-01, 5.14130449e-01, 2.18194638e-01, 8.50172258e-01],
       [6.53339968e-01, 5.82655745e-01, 9.93242398e-02, 8.17696322e-01],
       [4.81846700e-01, 6.69377018e-01, 3.61193167e-01, 7.63368407e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

In [24]:
scaled_X_train.min()

0.0

In [30]:
from keras.models import Sequential
from keras.layers import Dense

In [33]:
model = Sequential()

model.add(Dense(4,input_dim=4,activation='relu'))

model.add(Dense(8,activation='relu'))

model.add(Dense(1,activation='sigmoid'))

In [38]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [39]:
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
 - 1s - loss: 0.6711 - accuracy: 0.5495
Epoch 2/50
 - 0s - loss: 0.6667 - accuracy: 0.5495
Epoch 3/50
 - 0s - loss: 0.6615 - accuracy: 0.5571
Epoch 4/50
 - 0s - loss: 0.6560 - accuracy: 0.5669
Epoch 5/50
 - 0s - loss: 0.6487 - accuracy: 0.5865
Epoch 6/50
 - 0s - loss: 0.6368 - accuracy: 0.6137
Epoch 7/50
 - 0s - loss: 0.6250 - accuracy: 0.6279
Epoch 8/50
 - 0s - loss: 0.6089 - accuracy: 0.6431
Epoch 9/50
 - 0s - loss: 0.5884 - accuracy: 0.6779
Epoch 10/50
 - 0s - loss: 0.5682 - accuracy: 0.7095
Epoch 11/50
 - 0s - loss: 0.5509 - accuracy: 0.7301
Epoch 12/50
 - 0s - loss: 0.5342 - accuracy: 0.7508
Epoch 13/50
 - 0s - loss: 0.5197 - accuracy: 0.7552
Epoch 14/50
 - 0s - loss: 0.5061 - accuracy: 0.7628
Epoch 15/50
 - 0s - loss: 0.4927 - accuracy: 0.7715
Epoch 16/50
 - 0s - loss: 0.4806 - accuracy: 0.7726
Epoch 17/50
 - 0s - loss: 0.4689 - accuracy: 0.7813
Epoch 18/50
 - 0s - loss: 0.4570 - accuracy: 0.7845
Epoch 19/50
 - 0s - loss: 0.4460 - accuracy: 0.7911
Epoch 20/50
 - 0s - l

In [40]:
model.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    

In [41]:
model.metrics_names

['loss', 'accuracy']

In [43]:
from sklearn.metrics import confusion_matrix,classification_report

In [44]:
prediction=model.predict_classes(scaled_X_test)

In [45]:
confusion_matrix(y_test,prediction)

array([[253,   4],
       [ 20, 176]])

In [46]:
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

         0.0       0.93      0.98      0.95       257
         1.0       0.98      0.90      0.94       196

    accuracy                           0.95       453
   macro avg       0.95      0.94      0.95       453
weighted avg       0.95      0.95      0.95       453



In [47]:
model.save('mysupermodel.h5')

In [49]:
from keras.models import load_model

In [50]:
newmodel=load_model('mysupermodel.h5')

In [51]:
newmodel.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    